@startuml
'https://plantuml.com/class-diagram

object Frivilig
object Ansvarlig
object Aktivtet
object Vagt
object Person

Person <|-- Ansvarlig
Person <|-- Frivilig
Ansvarlig "1" -- "1..*" Aktivtet
Aktivtet "1" -- "1..*" Vagt
Frivilig "1" -- "1..*" Vagt

@enduml