@startuml
'https://plantuml.com/use-case-diagram
left to right direction

:Ansvarlig: as Ansvarlig
:Frivilig: as Frivilig

Frivilig --> (Register som frivilig)
Frivilig --> (Se vagtplan)
Frivilig --> (Rediger kontakt oplysninger)
Ansvarlig --> (Rediger i Frivilige oplysinnger)
Ansvarlig --> (Slette frivilige)
Ansvarlig --> (Tildele vagt til frivilig)
Ansvarlig --> (Se vagtplan)
Ansvarlig --> (Slet vagt)
Ansvarlig --> (Opret en vagt)
Ansvarlig --> (Se mine Informationer)
Frivilig --> (Se mine Informationer)



@enduml